### ISSUE TITLE
Electron clientside?

### ISSUE THREAD

**Issue by mgatelabs** [neruchev/i18next-electron-language-detector#1]
Can the language-detector be used with the client-side javascript of an electron app, or is it for the app side?  I'm trying to figure out how to use i18next for my electron app and its client-side pages and nothing has really shown how yet.

**Comment by neruchev** [comment]
@mgatelabs, both options will work, and I do not have a clear idea of which one is more correct.

a) You can parallel use i18next-electron-language-detector on the application side and i18next-browser-languageDetector on the client side - it will work.
or
b) You can detect the language, using i18next-electron-language-detector and transfer language string from main process to client. For example, using `webContents.send`. I use this variant.

Sorry for my English, it's awful :-)

**Comment by odensc** [comment]
Hi - I don't have time to make a PR right now, but it's as simple as changing the code to:

```js
import { remote, app } from 'electron';

export default {
  'init' : Function.prototype,
  'type' : 'languageDetector',
  'detect' : () => (app || remote.app).getLocale(),
  'cacheUserLanguage' : Function.prototype
};
```

(using `app` if available, otherwise falling back to `remote.app`)

**Comment by neruchev** [comment]
@odensc, fixed. Thanks!

**Comment by odensc** [comment]
@neruchev Sure but you forgot to import `remote` :)
