### ISSUE TITLE
Requiring a peer of i18next@8.*

### ISSUE THREAD

**Issue by ENT8R** [neruchev/i18next-electron-language-detector#2]
Is it really necessary to require a peer of i18next@8.* in https://github.com/neruchev/i18next-electron-language-detector/blob/d297afb44aa00bf69f91992d28cea379aea568c8/package.json#L24

Because everytime I want to install a new package with npm, it says this:
`npm WARN i18next-electron-language-detector@0.0.8 requires a peer of i18next@8.* but none was installed.`

I am using the current version of i18next (`10.0.7`) and it works without problems.
If you want to, I can create a PR to fix this.

**Comment by neruchev** [comment]
Fixed.

**Comment by ENT8R** [comment]
Great thanks!
